#!/bin/bash
# Get the newest 6.1 kernel from copr
set -eu

echo "Downloading the asus-kernel copr repo file"
cd /etc/yum.repos.d/
sudo wget https://copr.fedorainfracloud.org/coprs/lukenukem/asus-kernel/repo/fedora-37/lukenukem-asus-kernel-fedora-37.repo

echo "Installing the kernel from https://copr.fedorainfracloud.org/coprs/lukenukem/asus-kernel/" 
sudo rpm-ostree override replace --experimental --from repo=copr:copr.fedorainfracloud.org:lukenukem:asus-kernel kernel kernel-core kernel-modules kernel-modules-extra
